experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: facebook_book
  top_k: 50
  evaluation:
    cutoffs: [50]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    MostPop:
      meta:
        verbose: True
        save_recs: True
    Random:
      meta:
        verbose: True
        save_recs: True
    external.BPRMF:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 29
      lr: 0.0017664102849921446
      batch_size: 64
      epochs: 29
      factors: 64
      l_w: 0.05721092247228661
      seed: 123
    EASER:
      meta:
        verbose: True
        save_recs: True
      l2_norm: 1156.7327374740782
    external.LightGCN:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 2
      lr: 0.0028462729478462134
      epochs: 2
      factors: 64
      batch_size: 64
      l_w: 0.06184015598288455
      n_layers: 3
      seed: 123
    external.DGCF:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 4
      lr: 0.0007530315047454896
      epochs: 4
      factors: 64
      batch_size: 64
      l_w_bpr: 0.009012642853028007
      l_w_ind: 0.0008369458994883327
      ind_batch_size: 64
      n_layers: 1
      routing_iterations: 2
      intents: 4
      seed: 123
    KaHFMEmbeddings:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 19
      epochs: 19
      batch_size: 64
      lr: 0.0005922750643212075
      l_w: 0.02140563566611268
      l_b: 0
      loader: KAHFMLoader
      seed: 123
    external.KGFlex:
      loader: KGFlexLoader
      meta:
        verbose: True
        save_recs: True
        validation_rate: 44
      lr: 0.05794172109229535
      embedding: 1
      epochs: 44
      max_features_per_user: 1000
      batch_size: 64
    KGIN:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 20
      lr: 0.0004974556005249158
      batch_size: 64
      epochs: 20
      l2: 0.053885509726367936
      lfr: 0.008145222883360741
      emb: 64
      hops: 3
      n_fac: 4
      n_drop: True
      n_drop_r: 0.5
      m_drop: True
      m_drop_r: 0.1
      ind: distance
      seed: 123
      loader: KGINTSVLoader
    external.KGTORE:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 22
        validation_metric: nDCGRendle2020@10
      batch_size: 64
      lr: 0.00041155060113429626
      elr: 0.0027244852932723014
      l_w: 0.060707796238838284
      alpha: 0.6
      beta: 0.6
      epochs: 22
      factors: 64
      gamma: 0.9054246604017769
      ind_edges: 0.01
      n_layers: 3
      npr: 10
      criterion: entropy
      loader: KGTORETSVLoader
      seed: 123
