experiment:
  backend: pytorch
  dataset: facebook_book
  data_config:
    strategy: dataset
    dataset_path: ../data/{0}/dataset.tsv
    side_information:
      - dataloader: KGINTSVLoader
        attributes: ../data/{0}/kgat/kg.tsv
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 20
  gpu: 0
  external_models_path: ../external/models/__init__.py
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [nDCGRendle2020, nDCG, HR, Precision, Recall, MAP, MRR, ItemCoverage, UserCoverage, NumRetrieved, UserCoverage, Gini, SEntropy, EFD, EPC]
  models:
    external.KGAT:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        validation_metric: ItemCoverage
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        restore: False
      lr: [ loguniform, -8.90775527898, -6.90775527898 ]
      epochs: 200
      factors: 64
      batch_size: 64
      l_w: [ loguniform, -16.11809565095, -2.30258509299]  # [ quniform, 10e-5, 10, 100 ]
      n_layers: [ quniform, 2, 3, 1 ]
      loader: KGINTSVLoader

