experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KGINTSVLoader
        kg: ../data/{0}/kgat/kg.tsv
  dataset: movielens
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.KGAT:
      meta:
        hyper_max_evals: 20
        hyper_opt_alg: tpe
        verbose: True
        save_recs: False
        validation_rate: 1
        validation_metric: nDCGRendle2020@10
      lr: [ loguniform, -9.210340372, -5.298317367 ]
      epochs: 200
      factors: 64
      kg_factors: 64
      aggr: bi
      batch_size: 64
      l_w: [ loguniform, -11.512925465, 4.60517018599]
      weight_size: (64,32,16)
      message_dropout: [loguniform, -2.30258509299, -0.22314355131]
      loader: KGINTSVLoader
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: nDCGRendle2020@10
        verbose: True

