experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KGFlexLoader
        item_features: ../data/{0}/kgflex/item_features.tsv
  dataset: facebook_book
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.KGFlex:
      loader: KGFlexLoader
      meta:
        hyper_max_evals: 1
        hyper_opt_alg: tpe
        validation_rate: 8
        verbose: True
        save_weights: False
        save_recs: False
      lr: 1
      embedding: 3
      epochs: 100
      max_features_per_user: 1000
      batch_size: 256
