experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: KGTORETSVLoader
        kg: ../data/{0}/kgtore/kg.tsv
  dataset: facebook_book
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.KGTORE:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 57
        validation_metric: nDCGRendle2020@10
      batch_size: 64
      lr: 0.00041155060113429626
      elr: 0.0027244852932723014
      l_w: 0.060707796238838284
      alpha: 0.6
      beta: 0.6
      epochs: 57
      factors: 64
      gamma: 0.9054246604017769
      ind_edges: 0.01
      n_layers: 3
      npr: 10
      criterion: entropy
      loader: KGTORETSVLoader
      seed: 123
